metric_descriptions_long = {
    "minutes": "Total minutes played",
    "minutes_tip": "Minutes played when team in possession",
    "minutes_otip": "Minutes played when opponent in possession",
    "performance_count": "Total number of matches",
    "performance_included_count": "Number of matches included in aggregates",
    "performance_failed_count": "Number of matches excluded in aggregates",
    "passopportunity_count_total": "Total pass opportunities",
    "passopportunity_count_p30tip": "Pass opportunities per 30 min when team in possession",
    "pass_count_goalwithin10s_p30tip": "Pass leading to goal within 10 seconds per 30 mins when team in possession",
    "pass_count_shotwithin10s_p30tip": "Pass leading to shot within 10 seconds per 30 mins when team in possession",
    "pass_count_attempted_total": "Total passes attempted across all phases",
    "pass_count_attempted_p30tip": "Passes attempted per 30 mins when team in possession",
    "pass_count_completed_p30tip": "Passes completed per 30 mins when team in possession",
    "pass_pct_completed": "Pass completion percentage",
    "pass_avgxpass_attempted": "Average expected pass (xPass) value for attempted passes",
    "pass_avgdistance": "Average distance of attempted passes (meters)",
    "pass_count_longrange_attempted_p30tip": "Long-range passes attempted per 30 mins when team in possession",
    "pass_count_onetouch_attempted_p30tip": "One-touch passes attempted per 30 mins when team in possession",
    "pass_count_quickpass_attempted_p30tip": "Quick passes attempted per 30 mins when team in possession",
    "pass_count_onetouch_dangerous_attempted_p30tip": "Dngrerous one-touch passes attempted per 30 mins when team in possession",
    "pass_count_quickpass_dangerous_attempted_p30tip": "Dngrerous quick passes attempted per 30 mins when team in possession",
    "passopportunity_count_linebreak_p30tip": "Line-break pass opportunities per 30 mins when team in possession",
    "pass_count_linebreak_attempted_p30tip": "Line-break passes attempted per 30 mins when team in possession",
    "pass_count_linebreak_completed_p30tip": "Line-break passes completed per 30 mins when team in possession",
    "passopportunity_count_torun_p30tip": "Pass-to-run opportunities per 30 mins when team in possession",
    "pass_count_torun_attempted_p30tip": "Pass-to-run passes attempted per 30 mins when team in possession",
    "pass_count_torun_completed_p30tip": "Pass-to-run passes completed per 30 mins when team in possession",
    "pass_pct_torun_completed": "Pass-to-run completion percentage",
    "pass_avgxpass_torun_attempted": "Average xPass for attempted pass-to-run passes",
    "pass_count_torun_shotwithin10s_p30tip": "Pass-to-run leading to shot within 10s per 30 mins when team in possession",
    "pass_count_torun_goalwithin10s_p30tip": "Pass-to-run leading to goal within 10s per 30 mins when team in possession",
    "passopportunity_count_dangerous_p30tip": "Dngrerous pass opportunities per 30 mins when team in possession",
    "pass_count_dangerous_attempted_p30tip": "Dngrerous passes attempted per 30 mins when team in possession",
    "pass_pct_dangerous_completed": "Dngrerous pass completion percentage",
    "pass_count_dangerous_completed_p30tip": "Dngrerous passes completed per 30 mins when team in possession",
    "pass_count_difficultpass_attempted_p30tip": "Difficult passes attempted per 30 mins when team in possession",
    "offballrun_count_total": "Total off-ball runs across all types",
    "offballrun_count_p30tip": "Total off-ball runs per 30 mins when team in possession",
    "behindrun_count_p30tip": "Runs behind the defensive line per 30 mins when team in possession",
    "comingshortrun_count_p30tip": "Coming short runs per 30 mins when team in possession",
    "crossreceiverrun_count_p30tip": "Cross receiver runs per 30 mins when team in possession",
    "droppingoffrun_count_p30tip": "Dropping off runs per 30 mins when team in possession",
    "overlaprun_count_p30tip": "Overlap runs per 30 mins when team in possession",
    "pullinghalfspacerun_count_p30tip": "Pulling into half-space runs per 30 mins when team in possession",
    "pullingwiderun_count_p30tip": "Pulling wide runs per 30 mins when team in possession",
    "aheadoftheballrun_count_p30tip": "Runs ahead of the ball per 30 mins when team in possession",
    "supportrun_count_p30tip": "Support runs per 30 mins when team in possession",
    "underlaprun_count_p30tip": "Underlap runs per 30 mins when team in possession",
    "offballrun_count_shotwithin10s_p30tip": "Off-ball runs leading to shot within 10s per 30 mins when team in possession",
    "behindrun_count_shotwithin10s_p30tip": "Behind runs leading to shot within 10s per 30 mins when team in possession",
    "comingshortrun_count_shotwithin10s_p30tip": "Coming short runs leading to shot within 10s per 30 mins when team in possession",
    "crossreceiverrun_count_shotwithin10s_p30tip": "Cross receiver runs leading to shot within 10s per 30 mins when team in possession",
    "droppingoffrun_count_shotwithin10s_p30tip": "Dropping off runs leading to shot within 10s per 30 mins when team in possession",
    "overlaprun_count_shotwithin10s_p30tip": "Overlap runs leading to shot within 10s per 30 mins when team in possession",
    "pullinghalfspacerun_count_shotwithin10s_p30tip": "Half-space runs leading to shot within 10s per 30 mins when team in possession",
    "pullingwiderun_count_shotwithin10s_p30tip": "Pulling wide runs leading to shot within 10s per 30 mins when team in possession",
    "aheadoftheballrun_count_shotwithin10s_p30tip": "Ahead of ball runs leading to shot within 10s per 30 mins when team in possession",
    "supportrun_count_shotwithin10s_p30tip": "Support runs leading to shot within 10s per 30 mins when team in possession",
    "underlaprun_count_shotwithin10s_p30tip": "Underlap runs leading to shot within 10s per 30 mins when team in possession",
    "offballrun_count_goalwithin10s_p30tip": "Off-ball runs leading to goal within 10s per 30 mins when team in possession",
    "behindrun_count_goalwithin10s_p30tip": "Behind runs leading to goal within 10s per 30 mins when team in possession",
    "comingshortrun_count_goalwithin10s_p30tip": "Coming short runs leading to goal within 10s per 30 mins when team in possession",
    "crossreceiverrun_count_goalwithin10s_p30tip": "Cross receiver runs leading to goal within 10s per 30 mins when team in possession",
    "droppingoffrun_count_goalwithin10s_p30tip": "Dropping off runs leading to goal within 10s per 30 mins when team in possession",
    "overlaprun_count_goalwithin10s_p30tip": "Overlap runs leading to goal within 10s per 30 mins when team in possession",
    "pullinghalfspacerun_count_goalwithin10s_p30tip": "Half-space runs leading to goal within 10s per 30 mins when team in possession",
    "pullingwiderun_count_goalwithin10s_p30tip": "Pulling wide runs leading to goal within 10s per 30 mins when team in possession",
    "aheadoftheballrun_count_goalwithin10s_p30tip": "Ahead of ball runs leading to goal within 10s per 30 mins when team in possession",
    "supportrun_count_goalwithin10s_p30tip": "Support runs leading to goal within 10s per 30 mins when team in possession",
    "underlaprun_count_goalwithin10s_p30tip": "Underlap runs leading to goal within 10s per 30 mins when team in possession",
    "offballrun_count_targeted_p30tip": "Off-ball runs where player was targeted per 30 mins when team in possession",
    "behindrun_count_targeted_p30tip": "Behind runs where targeted per 30 mins when team in possession",
    "comingshortrun_count_targeted_p30tip": "Coming short runs where targeted per 30 mins when team in possession",
    "crossreceiverrun_count_targeted_p30tip": "Cross receiver runs where targeted per 30 mins when team in possession",
    "droppingoffrun_count_targeted_p30tip": "Dropping off runs where targeted per 30 mins when team in possession",
    "overlaprun_count_targeted_p30tip": "Overlap runs where targeted per 30 mins when team in possession",
    "pullinghalfspacerun_count_targeted_p30tip": "Half-space runs where targeted per 30 mins when team in possession",
    "pullingwiderun_count_targeted_p30tip": "Pulling wide runs where targeted per 30 mins when team in possession",
    "aheadoftheballrun_count_targeted_p30tip": "Ahead of ball runs where targeted per 30 mins when team in possession",
    "supportrun_count_targeted_p30tip": "Support runs where targeted per 30 mins when team in possession",
    "underlaprun_count_targeted_p30tip": "Underlap runs where targeted per 30 mins when team in possession",
    "offballrun_count_received_p30tip": "Off-ball runs where player received the ball per 30 mins when team in possession",
    "behindrun_count_received_p30tip": "Behind runs where ball received per 30 mins when team in possession",
    "comingshortrun_count_received_p30tip": "Coming short runs where ball received per 30 mins when team in possession",
    "crossreceiverrun_count_received_p30tip": "Cross receiver runs where ball received per 30 mins when team in possession",
    "droppingoffrun_count_received_p30tip": "Dropping off runs where ball received per 30 mins when team in possession",
    "overlaprun_count_received_p30tip": "Overlap runs where ball received per 30 mins when team in possession",
    "pullinghalfspacerun_count_received_p30tip": "Half-space runs where ball received per 30 mins when team in possession",
    "pullingwiderun_count_received_p30tip": "Pulling wide runs where ball received per 30 mins when team in possession",
    "aheadoftheballrun_count_received_p30tip": "Ahead of ball runs where ball received per 30 mins when team in possession",
    "supportrun_count_received_p30tip": "Support runs where ball received per 30 mins when team in possession",
    "underlaprun_count_received_p30tip": "Underlap runs where ball received per 30 mins when team in possession",
    "offballrun_avgdistance": "Average distance of off-ball runs (meters)",
    "behindrun_avgdistance": "Average distance of behind runs (meters)",
    "comingshortrun_avgdistance": "Average distance of coming short runs (meters)",
    "crossreceiverrun_avgdistance": "Average distance of cross receiver runs (meters)",
    "droppingoffrun_avgdistance": "Average distance of dropping off runs (meters)",
    "overlaprun_avgdistance": "Average distance of overlap runs (meters)",
    "pullinghalfspacerun_avgdistance": "Average distance of half-space runs (meters)",
    "pullingwiderun_avgdistance": "Average distance of pulling wide runs (meters)",
    "aheadoftheballrun_avgdistance": "Average distance of ahead of ball runs (meters)",
    "supportrun_avgdistance": "Average distance of support runs (meters)",
    "underlaprun_avgdistance": "Average distance of underlap runs (meters)",
    "offballrun_count_abovehsr_p30tip": "Off-ball runs above high-speed running threshold per 30 mins when team in possession",
    "behindrun_count_abovehsr_p30tip": "Behind runs above HSR threshold per 30 mins when team in possession",
    "comingshortrun_count_abovehsr_p30tip": "Coming short runs above HSR threshold per 30 mins when team in possession",
    "crossreceiverrun_count_abovehsr_p30tip": "Cross receiver runs above HSR threshold per 30 mins when team in possession",
    "droppingoffrun_count_abovehsr_p30tip": "Dropping off runs above HSR threshold per 30 mins when team in possession",
    "overlaprun_count_abovehsr_p30tip": "Overlap runs above HSR threshold per 30 mins when team in possession",
    "pullinghalfspacerun_count_abovehsr_p30tip": "Half-space runs above HSR threshold per 30 mins when team in possession",
    "pullingwiderun_count_abovehsr_p30tip": "Pulling wide runs above HSR threshold per 30 mins when team in possession",
    "aheadoftheballrun_count_abovehsr_p30tip": "Ahead of ball runs above HSR threshold per 30 mins when team in possession",
    "supportrun_count_abovehsr_p30tip": "Support runs above HSR threshold per 30 mins when team in possession",
    "underlaprun_count_abovehsr_p30tip": "Underlap runs above HSR threshold per 30 mins when team in possession",
    "offballrun_count_penaltyarea_p30tip": "Off-ball runs into penalty area per 30 mins when team in possession",
    "offballrun_count_dangerous_p30tip": "Dngrerous off-ball runs per 30 mins when team in possession",
    "behindrun_count_dangerous_p30tip": "Dngrerous behind runs per 30 mins when team in possession",
    "comingshortrun_count_dangerous_p30tip": "Dngrerous coming short runs per 30 mins when team in possession",
    "crossreceiverrun_count_dangerous_p30tip": "Dngrerous cross receiver runs per 30 mins when team in possession",
    "droppingoffrun_count_dangerous_p30tip": "Dngrerous dropping off runs per 30 mins when team in possession",
    "overlaprun_count_dangerous_p30tip": "Dngrerous overlap runs per 30 mins when team in possession",
    "pullinghalfspacerun_count_dangerous_p30tip": "Dngrerous half-space runs per 30 mins when team in possession",
    "pullingwiderun_count_dangerous_p30tip": "Dngrerous pulling wide runs per 30 mins when team in possession",
    "aheadoftheballrun_count_dangerous_p30tip": "Dngrerous ahead of ball runs per 30 mins when team in possession",
    "supportrun_count_dangerous_p30tip": "Dngrerous support runs per 30 mins when team in possession",
    "underlaprun_count_dangerous_p30tip": "Dngrerous underlap runs per 30 mins when team in possession",
    "offballrun_count_dangerous_targeted_p30tip": "Dngrerous off-ball runs where targeted per 30 mins when team in possession",
    "behindrun_count_dangerous_targeted_p30tip": "Dngrerous behind runs where targeted per 30 mins when team in possession",
    "comingshortrun_count_dangerous_targeted_p30tip": "Dngrerous coming short runs where targeted per 30 mins when team in possession",
    "crossreceiverrun_count_dangerous_targeted_p30tip": "Dngrerous cross receiver runs where targeted per 30 mins when team in possession",
    "droppingoffrun_count_dangerous_targeted_p30tip": "Dngrerous dropping off runs where targeted per 30 mins when team in possession",
    "overlaprun_count_dangerous_targeted_p30tip": "Dngrerous overlap runs where targeted per 30 mins when team in possession",
    "pullinghalfspacerun_count_dangerous_targeted_p30tip": "Dngrerous half-space runs where targeted per 30 mins when team in possession",
    "pullingwiderun_count_dangerous_targeted_p30tip": "Dngrerous pulling wide runs where targeted per 30 mins when team in possession",
    "aheadoftheballrun_count_dangerous_targeted_p30tip": "Dngrerous ahead of ball runs where targeted per 30 mins when team in possession",
    "supportrun_count_dangerous_targeted_p30tip": "Dngrerous support runs where targeted per 30 mins when team in possession",
    "underlaprun_count_dangerous_targeted_p30tip": "Dngrerous underlap runs where targeted per 30 mins when team in possession",
    "offballrun_count_dangerous_received_p30tip": "Dngrerous off-ball runs where ball received per 30 mins when team in possession",
    "behindrun_count_dangerous_received_p30tip": "Dngrerous behind runs where ball received per 30 mins when team in possession",
    "comingshortrun_count_dangerous_received_p30tip": "Dngrerous coming short runs where ball received per 30 mins when team in possession",
    "crossreceiverrun_count_dangerous_received_p30tip": "Dngrerous cross receiver runs where ball received per 30 mins when team in possession",
    "droppingoffrun_count_dangerous_received_p30tip": "Dngrerous dropping off runs where ball received per 30 mins when team in possession",
    "overlaprun_count_dangerous_received_p30tip": "Dngrerous overlap runs where ball received per 30 mins when team in possession",
    "pullinghalfspacerun_count_dangerous_received_p30tip": "Dngrerous half-space runs where ball received per 30 mins when team in possession",
    "pullingwiderun_count_dangerous_received_p30tip": "Dngrerous pulling wide runs where ball received per 30 mins when team in possession",
    "aheadoftheballrun_count_dangerous_received_p30tip": "Dngrerous ahead of ball runs where ball received per 30 mins when team in possession",
    "supportrun_count_dangerous_received_p30tip": "Dngrerous support runs where ball received per 30 mins when team in possession",
    "underlaprun_count_dangerous_received_p30tip": "Dngrerous underlap runs where ball received per 30 mins when team in possession",
}

metric_descriptions_short = {
    "minutes": "Min",
    "minutes_tip": "Min TiP",
    "minutes_otip": "Min OTiP",
    "performance_count": "Tot Mtch",
    "performance_included_count": "Incl Mtch",
    "performance_failed_count": "Excl Mtch",
    "passopportunity_count_total": "Tot Pass OP",
    "passopportunity_count_p30tip": "Pass OP p30mTiP",
    "pass_count_goalwithin10s_p30tip": "Pass => Goal w/in 10s p30mTiP",
    "pass_count_shotwithin10s_p30tip": "Pass => Shot w/in 10s p30mTiP",
    "pass_count_attempted_total": "Tot Pass Att",
    "pass_count_attempted_p30tip": "Pass Att p30mTiP",
    "pass_count_completed_p30tip": "Pass Comp p30mTiP",
    "pass_pct_completed": "Pass %",
    "pass_avgxpass_attempted": "Avg xPass Att",
    "pass_avgdistance": "Avg Pass Dist (m)",
    "pass_count_longrange_attempted_p30tip": "LR Pass Att p30mTiP",
    "pass_count_onetouch_attempted_p30tip": "1T Pass Att p30mTiP",
    "pass_count_quickpass_attempted_p30tip": "QP Att p30mTiP",
    "pass_count_onetouch_dangerous_attempted_p30tip": "Dngr 1T Pass Att p30mTiP",
    "pass_count_quickpass_dangerous_attempted_p30tip": "Dngr QP Att p30mTiP",
    "passopportunity_count_linebreak_p30tip": "LB Pass OP p30mTiP",
    "pass_count_linebreak_attempted_p30tip": "LB Pass Att p30mTiP",
    "pass_count_linebreak_completed_p30tip": "LB Pass Comp p30mTiP",
    "passopportunity_count_torun_p30tip": "P2R OP p30mTiP",
    "pass_count_torun_attempted_p30tip": "P2R Att p30mTiP",
    "pass_count_torun_completed_p30tip": "P2R Comp p30mTiP",
    "pass_pct_torun_completed": "P2R %",
    "pass_avgxpass_torun_attempted": "Avg xPass P2R Att",
    "pass_count_torun_shotwithin10s_p30tip": "P2R => Shot w/in 10s p30mTiP",
    "pass_count_torun_goalwithin10s_p30tip": "P2R => Goal w/in 10s p30mTiP",
    "passopportunity_count_dangerous_p30tip": "Dngr Pass OP p30mTiP",
    "pass_count_dangerous_attempted_p30tip": "Dngr Pass Att p30mTiP",
    "pass_pct_dangerous_completed": "Dngr Pass %",
    "pass_count_dangerous_completed_p30tip": "Dngr Pass Comp p30mTiP",
    "pass_count_difficultpass_attempted_p30tip": "Diff Pass Att p30mTiP",
    "offballrun_count_total": "Tot OBR",
    "offballrun_count_p30tip": "OBR p30mTiP",
    "behindrun_count_p30tip": "BR p30mTiP",
    "comingshortrun_count_p30tip": "CSR p30mTiP",
    "crossreceiverrun_count_p30tip": "CRR p30mTiP",
    "droppingoffrun_count_p30tip": "DOR p30mTiP",
    "overlaprun_count_p30tip": "OLR p30mTiP",
    "pullinghalfspacerun_count_p30tip": "PHSR p30mTiP",
    "pullingwiderun_count_p30tip": "PWR p30mTiP",
    "aheadoftheballrun_count_p30tip": "AOTB p30mTiP",
    "supportrun_count_p30tip": "SupR p30mTiP",
    "underlaprun_count_p30tip": "ULR p30mTiP",
    "offballrun_count_shotwithin10s_p30tip": "OBR => Shot w/in 10s p30mTiP",
    "behindrun_count_shotwithin10s_p30tip": "BR => Shot w/in 10s p30mTiP",
    "comingshortrun_count_shotwithin10s_p30tip": "CSR => Shot w/in 10s p30mTiP",
    "crossreceiverrun_count_shotwithin10s_p30tip": "CRR => Shot w/in 10s p30mTiP",
    "droppingoffrun_count_shotwithin10s_p30tip": "DOR => Shot w/in 10s p30mTiP",
    "overlaprun_count_shotwithin10s_p30tip": "OLR => Shot w/in 10s p30mTiP",
    "pullinghalfspacerun_count_shotwithin10s_p30tip": "PHSR => Shot w/in 10s p30mTiP",
    "pullingwiderun_count_shotwithin10s_p30tip": "PWR => Shot w/in 10s p30mTiP",
    "aheadoftheballrun_count_shotwithin10s_p30tip": "AOTB => Shot w/in 10s p30mTiP",
    "supportrun_count_shotwithin10s_p30tip": "SupR => Shot w/in 10s p30mTiP",
    "underlaprun_count_shotwithin10s_p30tip": "ULR => Shot w/in 10s p30mTiP",
    "offballrun_count_goalwithin10s_p30tip": "OBR => Goal w/in 10s p30mTiP",
    "behindrun_count_goalwithin10s_p30tip": "BR => Goal w/in 10s p30mTiP",
    "comingshortrun_count_goalwithin10s_p30tip": "CSR => Goal w/in 10s p30mTiP",
    "crossreceiverrun_count_goalwithin10s_p30tip": "CRR => Goal w/in 10s p30mTiP",
    "droppingoffrun_count_goalwithin10s_p30tip": "DOR => Goal w/in 10s p30mTiP",
    "overlaprun_count_goalwithin10s_p30tip": "OLR => Goal w/in 10s p30mTiP",
    "pullinghalfspacerun_count_goalwithin10s_p30tip": "PHSR => Goal w/in 10s p30mTiP",
    "pullingwiderun_count_goalwithin10s_p30tip": "PWR => Goal w/in 10s p30mTiP",
    "aheadoftheballrun_count_goalwithin10s_p30tip": "AOTB => Goal w/in 10s p30mTiP",
    "supportrun_count_goalwithin10s_p30tip": "SupR => Goal w/in 10s p30mTiP",
    "underlaprun_count_goalwithin10s_p30tip": "ULR => Goal w/in 10s p30mTiP",
    "offballrun_count_targeted_p30tip": "OBR tgt p30mTiP",
    "behindrun_count_targeted_p30tip": "BR tgt p30mTiP",
    "comingshortrun_count_targeted_p30tip": "CSR tgt p30mTiP",
    "crossreceiverrun_count_targeted_p30tip": "CRR tgt p30mTiP",
    "droppingoffrun_count_targeted_p30tip": "DOR tgt p30mTiP",
    "overlaprun_count_targeted_p30tip": "OLR tgt p30mTiP",
    "pullinghalfspacerun_count_targeted_p30tip": "PHSR tgt p30mTiP",
    "pullingwiderun_count_targeted_p30tip": "PWR tgt p30mTiP",
    "aheadoftheballrun_count_targeted_p30tip": "AOTB tgt p30mTiP",
    "supportrun_count_targeted_p30tip": "SupR tgt p30mTiP",
    "underlaprun_count_targeted_p30tip": "ULR tgt p30mTiP",
    "offballrun_count_received_p30tip": "OBR rcvd p30mTiP",
    "behindrun_count_received_p30tip": "BR rcvd p30mTiP",
    "comingshortrun_count_received_p30tip": "CSR rcvd p30mTiP",
    "crossreceiverrun_count_received_p30tip": "CRR rcvd p30mTiP",
    "droppingoffrun_count_received_p30tip": "DOR rcvd p30mTiP",
    "overlaprun_count_received_p30tip": "OLR rcvd p30mTiP",
    "pullinghalfspacerun_count_received_p30tip": "PHSR rcvd p30mTiP",
    "pullingwiderun_count_received_p30tip": "PWR rcvd p30mTiP",
    "aheadoftheballrun_count_received_p30tip": "AOTB rcvd p30mTiP",
    "supportrun_count_received_p30tip": "SupR rcvd p30mTiP",
    "underlaprun_count_received_p30tip": "ULR rcvd p30mTiP",
    "offballrun_avgdistance": "Avg OBR Dist (m)",
    "behindrun_avgdistance": "Avg BR Dist (m)",
    "comingshortrun_avgdistance": "Avg CSR Dist (m)",
    "crossreceiverrun_avgdistance": "Avg CRR Dist (m)",
    "droppingoffrun_avgdistance": "Avg DOR Dist (m)",
    "overlaprun_avgdistance": "Avg OLR Dist (m)",
    "pullinghalfspacerun_avgdistance": "Avg PHSR Dist (m)",
    "pullingwiderun_avgdistance": "Avg PWR Dist (m)",
    "aheadoftheballrun_avgdistance": "Avg AOTB Dist (m)",
    "supportrun_avgdistance": "Avg SupR Dist (m)",
    "underlaprun_avgdistance": "Avg ULR Dist (m)",
    "offballrun_count_abovehsr_p30tip": "OBR >HSR p30mTiP",
    "behindrun_count_abovehsr_p30tip": "BR >HSR p30mTiP",
    "comingshortrun_count_abovehsr_p30tip": "CSR >HSR p30mTiP",
    "crossreceiverrun_count_abovehsr_p30tip": "CRR >HSR p30mTiP",
    "droppingoffrun_count_abovehsr_p30tip": "DOR >HSR p30mTiP",
    "overlaprun_count_abovehsr_p30tip": "OLR >HSR p30mTiP",
    "pullinghalfspacerun_count_abovehsr_p30tip": "PHSR >HSR p30mTiP",
    "pullingwiderun_count_abovehsr_p30tip": "PWR >HSR p30mTiP",
    "aheadoftheballrun_count_abovehsr_p30tip": "AOTB >HSR p30mTiP",
    "supportrun_count_abovehsr_p30tip": "SupR >HSR p30mTiP",
    "underlaprun_count_abovehsr_p30tip": "ULR >HSR p30mTiP",
    "offballrun_count_penaltyarea_p30tip": "OBR PA p30mTiP",
    "offballrun_count_dangerous_p30tip": "Dngr OBR p30mTiP",
    "behindrun_count_dangerous_p30tip": "Dngr BR p30mTiP",
    "comingshortrun_count_dangerous_p30tip": "Dngr CSR p30mTiP",
    "crossreceiverrun_count_dangerous_p30tip": "Dngr CRR p30mTiP",
    "droppingoffrun_count_dangerous_p30tip": "Dngr DOR p30mTiP",
    "overlaprun_count_dangerous_p30tip": "Dngr OLR p30mTiP",
    "pullinghalfspacerun_count_dangerous_p30tip": "Dngr PHSR p30mTiP",
    "pullingwiderun_count_dangerous_p30tip": "Dngr PWR p30mTiP",
    "aheadoftheballrun_count_dangerous_p30tip": "Dngr AOTB p30mTiP",
    "supportrun_count_dangerous_p30tip": "Dngr SupR p30mTiP",
    "underlaprun_count_dangerous_p30tip": "Dngr ULR p30mTiP",
    "offballrun_count_dangerous_targeted_p30tip": "Dngr OBR tgt p30mTiP",
    "behindrun_count_dangerous_targeted_p30tip": "Dngr BR tgt p30mTiP",
    "comingshortrun_count_dangerous_targeted_p30tip": "Dngr CSR tgt p30mTiP",
    "crossreceiverrun_count_dangerous_targeted_p30tip": "Dngr CRR tgt p30mTiP",
    "droppingoffrun_count_dangerous_targeted_p30tip": "Dngr DOR tgt p30mTiP",
    "overlaprun_count_dangerous_targeted_p30tip": "Dngr OLR tgt p30mTiP",
    "pullinghalfspacerun_count_dangerous_targeted_p30tip": "Dngr PHSR tgt p30mTiP",
    "pullingwiderun_count_dangerous_targeted_p30tip": "Dngr PWR tgt p30mTiP",
    "aheadoftheballrun_count_dangerous_targeted_p30tip": "Dngr AOTB tgt p30mTiP",
    "supportrun_count_dangerous_targeted_p30tip": "Dngr SupR tgt p30mTiP",
    "underlaprun_count_dangerous_targeted_p30tip": "Dngr ULR tgt p30mTiP",
    "offballrun_count_dangerous_received_p30tip": "Dngr OBR rcvd p30mTiP",
    "behindrun_count_dangerous_received_p30tip": "Dngr BR rcvd p30mTiP",
    "comingshortrun_count_dangerous_received_p30tip": "Dngr CSR rcvd p30mTiP",
    "crossreceiverrun_count_dangerous_received_p30tip": "Dngr CRR rcvd p30mTiP",
    "droppingoffrun_count_dangerous_received_p30tip": "Dngr DOR rcvd p30mTiP",
    "overlaprun_count_dangerous_received_p30tip": "Dngr OLR rcvd p30mTiP",
    "pullinghalfspacerun_count_dangerous_received_p30tip": "Dngr PHSR rcvd p30mTiP",
    "pullingwiderun_count_dangerous_received_p30tip": "Dngr PWR rcvd p30mTiP",
    "aheadoftheballrun_count_dangerous_received_p30tip": "Dngr AOTB rcvd p30mTiP",
    "supportrun_count_dangerous_received_p30tip": "Dngr SupR rcvd p30mTiP",
    "underlaprun_count_dangerous_received_p30tip": "Dngr ULR rcvd p30mTiP",
}

physical_metrics = {
    "player_name": "Full name of the player",
    "player_short_name": "Short/display name of the player",
    "player_id": "Unique identifier for the player",
    "player_birthdate": "Date of birth of the player",
    "team_name": "Name of the team",
    "team_id": "Unique identifier for the team",
    "competition_name": "Name of the competition (e.g., AUS - A-League)",
    "competition_id": "Unique identifier for the competition",
    "season_name": "Name of the season (e.g., 2024/2025)",
    "season_id": "Unique identifier for the season",
    "position_group": "Position group the player played in for this record",
    "minutes_full_all": "Total minutes played across all phases",
    "minutes_full_tip": "Minutes played in team in possession phases",
    "minutes_full_otip": "Minutes played in opponent in possession phases",
    "count_match": "Number of matches played",
    "count_match_failed": "Number of matches excluded/failed",
    "total_distance_full_all": "Total distance covered across all phases (meters)",
    "total_metersperminute_full_all": "Total meters per minute across all phases",
    "running_distance_full_all": "Running distance covered across all phases (meters)",
    "hsr_distance_full_all": "High-speed running distance across all phases (meters)",
    "hsr_count_full_all": "Number of high-speed running efforts across all phases",
    "sprint_distance_full_all": "Sprint distance covered across all phases (meters)",
    "sprint_count_full_all": "Number of sprint efforts across all phases",
    "hi_distance_full_all": "High-intensity distance across all phases (meters)",
    "hi_count_full_all": "Number of high-intensity efforts across all phases",
    "medaccel_count_full_all": "Medium acceleration count across all phases",
    "highaccel_count_full_all": "High acceleration count across all phases",
    "meddecel_count_full_all": "Medium deceleration count across all phases",
    "highdecel_count_full_all": "High deceleration count across all phases",
    "explacceltohsr_count_full_all": "Explosive accelerations to HSR count across all phases",
    "timetohsr_top3": "Average time to reach HSR (top 3 efforts) in seconds",
    "explacceltosprint_count_full_all": "Explosive accelerations to sprint count across all phases",
    "timetosprint_top3": "Average time to reach sprint speed (top 3 efforts) in seconds",
    "psv99": "Peak sprint velocity (99th percentile) in km/h",
    "psv99_top5": "Average peak sprint velocity of top 5 efforts in km/h",
    "total_distance_full_tip": "Total distance covered in team in possession (meters)",
    "total_metersperminute_full_tip": "Meters per minute in team in possession",
    "running_distance_full_tip": "Running distance in team in possession (meters)",
    "hsr_distance_full_tip": "High-speed running distance in team in possession (meters)",
    "hsr_count_full_tip": "High-speed running count in team in possession",
    "sprint_distance_full_tip": "Sprint distance in team in possession (meters)",
    "sprint_count_full_tip": "Sprint count in team in possession",
    "hi_distance_full_tip": "High-intensity distance in team in possession (meters)",
    "hi_count_full_tip": "High-intensity count in team in possession",
    "medaccel_count_full_tip": "Medium acceleration count in team in possession",
    "highaccel_count_full_tip": "High acceleration count in team in possession",
    "meddecel_count_full_tip": "Medium deceleration count in team in possession",
    "highdecel_count_full_tip": "High deceleration count in team in possession",
    "explacceltohsr_count_full_tip": "Explosive accelerations to HSR in team in possession",
    "explacceltosprint_count_full_tip": "Explosive accelerations to sprint in team in possession",
    "total_distance_full_otip": "Total distance covered in opponent in possession (meters)",
    "total_metersperminute_full_otip": "Meters per minute in opponent in possession",
    "running_distance_full_otip": "Running distance in opponent in possession (meters)",
    "hsr_distance_full_otip": "High-speed running distance in opponent in possession (meters)",
    "hsr_count_full_otip": "High-speed running count in opponent in possession",
    "sprint_distance_full_otip": "Sprint distance in opponent in possession (meters)",
    "sprint_count_full_otip": "Sprint count in opponent in possession",
    "hi_distance_full_otip": "High-intensity distance in opponent in possession (meters)",
    "hi_count_full_otip": "High-intensity count in opponent in possession",
    "medaccel_count_full_otip": "Medium acceleration count in opponent in possession",
    "highaccel_count_full_otip": "High acceleration count in opponent in possession",
    "meddecel_count_full_otip": "Medium deceleration count in opponent in possession",
    "highdecel_count_full_otip": "High deceleration count in opponent in possession",
    "explacceltohsr_count_full_otip": "Explosive accelerations to HSR in opponent in possession",
    "explacceltosprint_count_full_otip": "Explosive accelerations to sprint in opponent in possession",
}